[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package]
name = "iallai-os"
version = "0.1.0"
authors = ["iallai <iallai.info@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
